# Generated by Django 4.2.1 on 2023-05-04 11:27

from django.db import migrations
from django.conf import settings


def create_data(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user = User(pk=1, username="auth0user", is_active=True, email="auth0user@auth.com")
    user.save()


class Migration(migrations.Migration):
    dependencies = []
    operations = [
        migrations.RunPython(create_data),
    ]
